In [3]:
import pandas as pd
import os

# Definimos la ruta donde se guardó el archivo
csv_path = r'C:\Users\PC\Desktop\3ºGIDIA\PD2\PD2-conducIA\data\processed\tlc_clean\csv_final.csv'

# Verificamos si el archivo existe antes de intentar leerlo
if os.path.exists(csv_path):
    # Cargamos el dataset
    df_verificacion = pd.read_csv(csv_path)
    
    print(f"--- PRIMERAS FILAS (Inicio del año/Diciembre anterior) ---")
    display(df_verificacion.head(5))
    
    print(f"\n" + "="*50 + "\n")
    
    print(f"--- ÚLTIMAS FILAS (Final del año actual) ---")
    display(df_verificacion.tail(5))
    
    print(f"\nDimensiones totales del dataset: {df_verificacion.shape[0]:,} filas y {df_verificacion.shape[1]} columnas.")
else:
    print(f"Error: No se encontró el archivo en {csv_path}. Asegúrate de haber ejecutado el script .py primero.")

--- PRIMERAS FILAS (Inicio del año/Diciembre anterior) ---

,fecha_inicio,fecha_fin,origen_id,destino_id,num_pasajeros,distancia,propina,tipo_pago,duracion_min,velocidad_mph,...,destino_barrio,temp_c,precipitation,viento_kmh,lluvia,nieve,es_festivo,evento_tipo,num_eventos,mes_num
0,2024-12-01 00:00:34,2024-12-01 00:10:21,163,229,1.0,1.40,3.00,1.0,9.783333,8.586031,...,Manhattan,-2.0,0.0,10.3,0,0,0,No hay,0,12
1,2024-12-01 00:00:36,2024-12-01 00:17:36,226,107,NaN,5.38,6.38,NaN,17.000000,18.988236,...,Manhattan,-2.1,0.0,9.3,0,0,0,No hay,0,12
2,2024-12-01 00:00:50,2024-12-01 00:19:51,56,80,NaN,5.14,0.00,NaN,19.016667,16.217353,...,Brooklyn,-2.1,0.0,9.3,0,0,0,No hay,0,12
3,2024-12-01 00:01:09,2024-12-01 00:22:08,116,162,NaN,7.21,0.00,NaN,20.983333,20.616362,...,Manhattan,-2.0,0.0,10.3,0,0,0,No hay,0,12
4,2024-12-01 00:01:14,2024-12-01 00:11:02,168,167,NaN,2.00,0.00,NaN,9.800000,12.244898,...,Bronx,-1.6,0.0,11.7,0,0,0,No hay,0,12

==================================================

--- ÚLTIMAS FILAS (Final del año actual) ---

,fecha_inicio,fecha_fin,origen_id,destino_id,num_pasajeros,distancia,propina,tipo_pago,duracion_min,velocidad_mph,...,destino_barrio,temp_c,precipitation,viento_kmh,lluvia,nieve,es_festivo,evento_tipo,num_eventos,mes_num
2013475,2025-11-30 23:55:31,2025-11-30 23:59:17,100,48,NaN,0.53,0.00,NaN,3.766667,8.442477,...,Manhattan,4.0,0.0,14.5,0,0,0,No hay,0,11
2013476,2025-11-30 23:56:04,2025-12-01 00:04:00,136,169,NaN,1.28,1.00,NaN,7.933333,9.680672,...,Bronx,4.1,0.0,15.1,0,0,0,No hay,0,11
2013477,2025-11-30 23:58:42,2025-12-01 00:08:55,143,162,NaN,2.58,5.81,NaN,10.216667,15.151712,...,Manhattan,4.0,0.0,14.5,0,0,0,No hay,0,11
2013478,2025-11-30 23:58:54,2025-12-01 00:34:04,132,143,NaN,18.21,6.29,NaN,35.166667,31.069193,...,Manhattan,4.0,0.0,11.4,0,0,0,No hay,0,11
2013479,2025-11-30 23:59:28,2025-12-01 00:05:36,198,36,NaN,1.40,0.00,NaN,6.133333,13.695652,...,Brooklyn,4.0,0.0,11.4,0,0,0,No hay,0,11

Dimensiones totales del dataset: 2,013,480 filas y 27 columnas.